export default [
  { code: 0x00, length: 1, mnemonic: 'NOP' },

  { code: 0x01, length: 3, mnemonic: 'LXI B,d16' },
  { code: 0x02, length: 1, mnemonic: 'STAX B' },
  { code: 0x03, length: 1, mnemonic: 'INX B' },
  { code: 0x04, length: 1, mnemonic: 'INR B' },
  { code: 0x05, length: 1, mnemonic: 'DCR B' },
  { code: 0x06, length: 2, mnemonic: 'MVI B,d8' },
  { code: 0x07, length: 1, mnemonic: 'RLC' },

  { code: 0x08, length: 1, mnemonic: 'NOP' },

  { code: 0x09, length: 1, mnemonic: 'DAD B' },
  { code: 0x0a, length: 1, mnemonic: 'LDAX B' },
  { code: 0x0b, length: 1, mnemonic: 'DCX B' },
  { code: 0x0c, length: 1, mnemonic: 'INR C' },
  { code: 0x0d, length: 1, mnemonic: 'DCR C' },
  { code: 0x0e, length: 2, mnemonic: 'MVI C,d8' },
  { code: 0x0f, length: 1, mnemonic: 'RRC' },

  { code: 0x10, length: 1, mnemonic: 'NOP' },

  { code: 0x11, length: 3, mnemonic: 'LXI D,d16' },
  { code: 0x12, length: 1, mnemonic: 'STAX D' },
  { code: 0x13, length: 1, mnemonic: 'INX D' },
  { code: 0x14, length: 1, mnemonic: 'INR D' },
  { code: 0x15, length: 1, mnemonic: 'DCR D' },
  { code: 0x16, length: 2, mnemonic: 'MVI D,d8' },
  { code: 0x17, length: 1, mnemonic: 'RAL' },

  { code: 0x18, length: 1, mnemonic: 'NOP' },

  { code: 0x19, length: 1, mnemonic: 'DAD D' },
  { code: 0x1a, length: 1, mnemonic: 'LDAX D' },
  { code: 0x1b, length: 1, mnemonic: 'DCX D' },
  { code: 0x1c, length: 1, mnemonic: 'INR E' },
  { code: 0x1d, length: 1, mnemonic: 'DCR E' },
  { code: 0x1e, length: 2, mnemonic: 'MVI E,d8' },
  { code: 0x1f, length: 1, mnemonic: 'RAR' },

  { code: 0x20, length: 1, mnemonic: 'NOP' },

  { code: 0x21, length: 3, mnemonic: 'LXI H,d16' },
  { code: 0x22, length: 3, mnemonic: 'SHLD a16' },
  { code: 0x23, length: 1, mnemonic: 'INX H' },
  { code: 0x24, length: 1, mnemonic: 'INR H' },
  { code: 0x25, length: 1, mnemonic: 'DCR H' },
  { code: 0x26, length: 2, mnemonic: 'MVI H,d8' },
  { code: 0x27, length: 1, mnemonic: 'DAA' },

  { code: 0x28, length: 1, mnemonic: 'NOP' },

  { code: 0x29, length: 1, mnemonic: 'DAD H' },
  { code: 0x2a, length: 3, mnemonic: 'LHLD a16' },
  { code: 0x2b, length: 1, mnemonic: 'DCX H' },
  { code: 0x2c, length: 1, mnemonic: 'INR L' },
  { code: 0x2d, length: 1, mnemonic: 'DCR L' },
  { code: 0x2e, length: 2, mnemonic: 'MVI L,d8' },
  { code: 0x2f, length: 1, mnemonic: 'CMA' },

  { code: 0x30, length: 1, mnemonic: 'NOP' },

  { code: 0x31, length: 3, mnemonic: 'LXI SP,d16' },
  { code: 0x32, length: 3, mnemonic: 'STA a16' },
  { code: 0x33, length: 1, mnemonic: 'INX SP' },
  { code: 0x34, length: 1, mnemonic: 'INR M' },
  { code: 0x35, length: 1, mnemonic: 'DCR M' },
  { code: 0x36, length: 2, mnemonic: 'MVI M,d8' },
  { code: 0x37, length: 1, mnemonic: 'STC' },

  { code: 0x38, length: 1, mnemonic: 'NOP' },

  { code: 0x39, length: 1, mnemonic: 'DAD SP' },
  { code: 0x3a, length: 3, mnemonic: 'LDA a16' },
  { code: 0x3b, length: 1, mnemonic: 'DCX SP' },
  { code: 0x3c, length: 1, mnemonic: 'INR A' },
  { code: 0x3d, length: 1, mnemonic: 'DCR A' },
  { code: 0x3e, length: 2, mnemonic: 'MVI A,d8' },
  { code: 0x3f, length: 1, mnemonic: 'CMC' },

  { code: 0x40, length: 1, mnemonic: 'MOV B,B' },
  { code: 0x41, length: 1, mnemonic: 'MOV B,C' },
  { code: 0x42, length: 1, mnemonic: 'MOV B,D' },
  { code: 0x43, length: 1, mnemonic: 'MOV B,E' },
  { code: 0x44, length: 1, mnemonic: 'MOV B,H' },
  { code: 0x45, length: 1, mnemonic: 'MOV B,L' },
  { code: 0x46, length: 1, mnemonic: 'MOV B,M' },
  { code: 0x47, length: 1, mnemonic: 'MOV B,A' },

  { code: 0x48, length: 1, mnemonic: 'MOV C,B' },
  { code: 0x49, length: 1, mnemonic: 'MOV C,C' },
  { code: 0x4a, length: 1, mnemonic: 'MOV C,D' },
  { code: 0x4b, length: 1, mnemonic: 'MOV C,E' },
  { code: 0x4c, length: 1, mnemonic: 'MOV C,H' },
  { code: 0x4d, length: 1, mnemonic: 'MOV C,L' },
  { code: 0x4e, length: 1, mnemonic: 'MOV C,M' },
  { code: 0x4f, length: 1, mnemonic: 'MOV C,A' },

  { code: 0x50, length: 1, mnemonic: 'MOV D,B' },
  { code: 0x51, length: 1, mnemonic: 'MOV D,C' },
  { code: 0x52, length: 1, mnemonic: 'MOV D,D' },
  { code: 0x53, length: 1, mnemonic: 'MOV D,E' },
  { code: 0x54, length: 1, mnemonic: 'MOV D,H' },
  { code: 0x55, length: 1, mnemonic: 'MOV D,L' },
  { code: 0x56, length: 1, mnemonic: 'MOV D,M' },
  { code: 0x57, length: 1, mnemonic: 'MOV D,A' },

  { code: 0x58, length: 1, mnemonic: 'MOV E,B' },
  { code: 0x59, length: 1, mnemonic: 'MOV E,C' },
  { code: 0x5a, length: 1, mnemonic: 'MOV E,D' },
  { code: 0x5b, length: 1, mnemonic: 'MOV E,E' },
  { code: 0x5c, length: 1, mnemonic: 'MOV E,H' },
  { code: 0x5d, length: 1, mnemonic: 'MOV E,L' },
  { code: 0x5e, length: 1, mnemonic: 'MOV E,M' },
  { code: 0x5f, length: 1, mnemonic: 'MOV E,A' },

  { code: 0x60, length: 1, mnemonic: 'MOV H,B' },
  { code: 0x61, length: 1, mnemonic: 'MOV H,C' },
  { code: 0x62, length: 1, mnemonic: 'MOV H,D' },
  { code: 0x63, length: 1, mnemonic: 'MOV H,E' },
  { code: 0x64, length: 1, mnemonic: 'MOV H,H' },
  { code: 0x65, length: 1, mnemonic: 'MOV H,L' },
  { code: 0x66, length: 1, mnemonic: 'MOV H,M' },
  { code: 0x67, length: 1, mnemonic: 'MOV H,A' },

  { code: 0x68, length: 1, mnemonic: 'MOV L,B' },
  { code: 0x69, length: 1, mnemonic: 'MOV L,C' },
  { code: 0x6a, length: 1, mnemonic: 'MOV L,D' },
  { code: 0x6b, length: 1, mnemonic: 'MOV L,E' },
  { code: 0x6c, length: 1, mnemonic: 'MOV L,H' },
  { code: 0x6d, length: 1, mnemonic: 'MOV L,L' },
  { code: 0x6e, length: 1, mnemonic: 'MOV L,M' },
  { code: 0x6f, length: 1, mnemonic: 'MOV L,A' },

  { code: 0x70, length: 1, mnemonic: 'MOV M,B' },
  { code: 0x71, length: 1, mnemonic: 'MOV M,C' },
  { code: 0x72, length: 1, mnemonic: 'MOV M,D' },
  { code: 0x73, length: 1, mnemonic: 'MOV M,E' },
  { code: 0x74, length: 1, mnemonic: 'MOV M,H' },
  { code: 0x75, length: 1, mnemonic: 'MOV M,L' },
  { code: 0x76, length: 1, mnemonic: 'HLT' },
  { code: 0x77, length: 1, mnemonic: 'MOV M,A' },

  { code: 0x78, length: 1, mnemonic: 'MOV A,B' },
  { code: 0x79, length: 1, mnemonic: 'MOV A,C' },
  { code: 0x7a, length: 1, mnemonic: 'MOV A,D' },
  { code: 0x7b, length: 1, mnemonic: 'MOV A,E' },
  { code: 0x7c, length: 1, mnemonic: 'MOV A,H' },
  { code: 0x7d, length: 1, mnemonic: 'MOV A,L' },
  { code: 0x7e, length: 1, mnemonic: 'MOV A,M' },
  { code: 0x7f, length: 1, mnemonic: 'MOV A,A' },

  { code: 0x80, length: 1, mnemonic: 'ADD B' },
  { code: 0x81, length: 1, mnemonic: 'ADD C' },
  { code: 0x82, length: 1, mnemonic: 'ADD D' },
  { code: 0x83, length: 1, mnemonic: 'ADD E' },
  { code: 0x84, length: 1, mnemonic: 'ADD H' },
  { code: 0x85, length: 1, mnemonic: 'ADD L' },
  { code: 0x86, length: 1, mnemonic: 'ADD M' },
  { code: 0x87, length: 1, mnemonic: 'ADD A' },

  { code: 0x88, length: 1, mnemonic: 'ADC B' },
  { code: 0x89, length: 1, mnemonic: 'ADC C' },
  { code: 0x8a, length: 1, mnemonic: 'ADC D' },
  { code: 0x8b, length: 1, mnemonic: 'ADC E' },
  { code: 0x8c, length: 1, mnemonic: 'ADC H' },
  { code: 0x8d, length: 1, mnemonic: 'ADC L' },
  { code: 0x8e, length: 1, mnemonic: 'ADC M' },
  { code: 0x8f, length: 1, mnemonic: 'ADC A' },

  { code: 0x90, length: 1, mnemonic: 'SUB B' },
  { code: 0x91, length: 1, mnemonic: 'SUB C' },
  { code: 0x92, length: 1, mnemonic: 'SUB D' },
  { code: 0x93, length: 1, mnemonic: 'SUB E' },
  { code: 0x94, length: 1, mnemonic: 'SUB H' },
  { code: 0x95, length: 1, mnemonic: 'SUB L' },
  { code: 0x96, length: 1, mnemonic: 'SUB M' },
  { code: 0x97, length: 1, mnemonic: 'SUB A' },

  { code: 0x98, length: 1, mnemonic: 'SBB B' },
  { code: 0x99, length: 1, mnemonic: 'SBB C' },
  { code: 0x9a, length: 1, mnemonic: 'SBB D' },
  { code: 0x9b, length: 1, mnemonic: 'SBB E' },
  { code: 0x9c, length: 1, mnemonic: 'SBB H' },
  { code: 0x9d, length: 1, mnemonic: 'SBB L' },
  { code: 0x9e, length: 1, mnemonic: 'SBB M' },
  { code: 0x9f, length: 1, mnemonic: 'SBB A' },

  { code: 0xa0, length: 1, mnemonic: 'ANA B' },
  { code: 0xa1, length: 1, mnemonic: 'ANA C' },
  { code: 0xa2, length: 1, mnemonic: 'ANA D' },
  { code: 0xa3, length: 1, mnemonic: 'ANA E' },
  { code: 0xa4, length: 1, mnemonic: 'ANA H' },
  { code: 0xa5, length: 1, mnemonic: 'ANA L' },
  { code: 0xa6, length: 1, mnemonic: 'ANA M' },
  { code: 0xa7, length: 1, mnemonic: 'ANA A' },

  { code: 0xa8, length: 1, mnemonic: 'XRA B' },
  { code: 0xa9, length: 1, mnemonic: 'XRA C' },
  { code: 0xaa, length: 1, mnemonic: 'XRA D' },
  { code: 0xab, length: 1, mnemonic: 'XRA E' },
  { code: 0xac, length: 1, mnemonic: 'XRA H' },
  { code: 0xad, length: 1, mnemonic: 'XRA L' },
  { code: 0xae, length: 1, mnemonic: 'XRA M' },
  { code: 0xaf, length: 1, mnemonic: 'XRA A' },

  { code: 0xb0, length: 1, mnemonic: 'ORA B' },
  { code: 0xb1, length: 1, mnemonic: 'ORA C' },
  { code: 0xb2, length: 1, mnemonic: 'ORA D' },
  { code: 0xb3, length: 1, mnemonic: 'ORA E' },
  { code: 0xb4, length: 1, mnemonic: 'ORA H' },
  { code: 0xb5, length: 1, mnemonic: 'ORA L' },
  { code: 0xb6, length: 1, mnemonic: 'ORA M' },
  { code: 0xb7, length: 1, mnemonic: 'ORA A' },

  { code: 0xb8, length: 1, mnemonic: 'CMP B' },
  { code: 0xb9, length: 1, mnemonic: 'CMP C' },
  { code: 0xba, length: 1, mnemonic: 'CMP D' },
  { code: 0xbb, length: 1, mnemonic: 'CMP E' },
  { code: 0xbc, length: 1, mnemonic: 'CMP H' },
  { code: 0xbd, length: 1, mnemonic: 'CMP L' },
  { code: 0xbe, length: 1, mnemonic: 'CMP M' },
  { code: 0xbf, length: 1, mnemonic: 'CMP A' },

  { code: 0xc0, length: 1, mnemonic: 'RNZ' },
  { code: 0xc1, length: 1, mnemonic: 'POP B' },
  { code: 0xc2, length: 3, mnemonic: 'JNZ a16' },
  { code: 0xc3, length: 3, mnemonic: 'JMP a16' },
  { code: 0xc4, length: 3, mnemonic: 'CNZ a16' },
  { code: 0xc5, length: 1, mnemonic: 'PUSH B' },
  { code: 0xc6, length: 2, mnemonic: 'ADI d8' },
  { code: 0xc7, length: 1, mnemonic: 'RST 0' },

  { code: 0xc8, length: 1, mnemonic: 'RZ' },
  { code: 0xc9, length: 1, mnemonic: 'RET' },
  { code: 0xca, length: 3, mnemonic: 'JZ a16' },
  { code: 0xcb, length: 1, mnemonic: 'NOP' },
  { code: 0xcc, length: 3, mnemonic: 'CZ a16' },
  { code: 0xcd, length: 3, mnemonic: 'CALL a16' },
  { code: 0xce, length: 2, mnemonic: 'ACI d8' },
  { code: 0xcf, length: 1, mnemonic: 'RST 1' },

  { code: 0xd0, length: 1, mnemonic: 'RNC' },
  { code: 0xd1, length: 1, mnemonic: 'POP D' },
  { code: 0xd2, length: 3, mnemonic: 'JNC a16' },
  { code: 0xd3, length: 1, mnemonic: 'OUT d8' },
  { code: 0xd4, length: 3, mnemonic: 'CNC a16' },
  { code: 0xd5, length: 1, mnemonic: 'PUSH D' },
  { code: 0xd6, length: 2, mnemonic: 'SUI d8' },
  { code: 0xd7, length: 1, mnemonic: 'RST 2' },

  { code: 0xd8, length: 1, mnemonic: 'RC' },
  { code: 0xd9, length: 1, mnemonic: 'NOP' },
  { code: 0xda, length: 3, mnemonic: 'JC a16' },
  { code: 0xdb, length: 1, mnemonic: 'IN d8' },
  { code: 0xdc, length: 3, mnemonic: 'CC a16' },
  { code: 0xdd, length: 1, mnemonic: 'NOP' },
  { code: 0xde, length: 2, mnemonic: 'SBI d8' },
  { code: 0xdf, length: 1, mnemonic: 'RST 3' },

  { code: 0xe0, length: 1, mnemonic: 'RPO' },
  { code: 0xe1, length: 1, mnemonic: 'POP H' },
  { code: 0xe2, length: 1, mnemonic: 'JPO a16' },
  { code: 0xe3, length: 1, mnemonic: 'XTHL' },
  { code: 0xe4, length: 3, mnemonic: 'CPO a16' },
  { code: 0xe5, length: 1, mnemonic: 'PUSH H' },
  { code: 0xe6, length: 2, mnemonic: 'ANI d8' },
  { code: 0xe7, length: 1, mnemonic: 'RST 4' },

  { code: 0xe8, length: 1, mnemonic: 'RPE' },
  { code: 0xe9, length: 1, mnemonic: 'PCHL' },
  { code: 0xea, length: 3, mnemonic: 'JPE a16' },
  { code: 0xeb, length: 1, mnemonic: 'XCHG' },
  { code: 0xec, length: 3, mnemonic: 'CPE a16' },
  { code: 0xed, length: 1, mnemonic: 'NOP' },
  { code: 0xee, length: 2, mnemonic: 'XRI d8' },
  { code: 0xef, length: 1, mnemonic: 'RST 5' },

  { code: 0xf0, length: 1, mnemonic: 'RP' },
  { code: 0xf1, length: 1, mnemonic: 'POP PSW' },
  { code: 0xf2, length: 3, mnemonic: 'JP a16' },
  { code: 0xf3, length: 1, mnemonic: 'DI' },
  { code: 0xf4, length: 3, mnemonic: 'CP a16' },
  { code: 0xf5, length: 1, mnemonic: 'PUSH PSW' },
  { code: 0xf6, length: 2, mnemonic: 'ORI d8' },
  { code: 0xf7, length: 1, mnemonic: 'RST 6' },

  { code: 0xf8, length: 1, mnemonic: 'RM' },
  { code: 0xf9, length: 1, mnemonic: 'SPHL' },
  { code: 0xfa, length: 3, mnemonic: 'JM a16' },
  { code: 0xfb, length: 1, mnemonic: 'EI' },
  { code: 0xfc, length: 3, mnemonic: 'CM a16' },
  { code: 0xfd, length: 1, mnemonic: 'NOP' },
  { code: 0xfe, length: 2, mnemonic: 'CPI a16' },
  { code: 0xff, length: 1, mnemonic: 'RST 7' }
]
